"""
routes/alignment.py

Alignment Dashboard Blueprint — Non-Blocking Coreference Claim Card Review.

Purpose:
    Provides the optional, non-blocking UI for reviewing provisional coreference
    assumptions generated by the ingestion pipeline. The FSM never waits for
    human review here — all coreference links are classified by confidence tier
    and the FSM proceeds with mid-confidence Epistemic Beliefs marked as unconfirmed.

    Claim Cards represent one provisional coreference link each. The author can:
    - Confirm a link (promotes it from provisional to confirmed in Graphiti).
    - Contradict a link (drops the edge from Graphiti).
    - Skip a link (leaves it as provisional for the 200-token window heuristic
      in node_commit_transaction to resolve automatically at chapter boundaries).

    Key routes:
    GET  /alignment          — Renders the Claim Card review view (templates/alignment.html).
    GET  /alignment/claims   — Returns JSON array of pending provisional coreference claims.
    POST /alignment/confirm  — Confirms a provisional link (upgrades to high-confidence).
    POST /alignment/contradict — Contradicts a provisional link (drops Graphiti edge).
    POST /alignment/ingest   — Initiates manuscript ingestion as a background async task.

Architecture role:
    - All human review actions are non-blocking — the FSM does not pause awaiting them.
    - Provisional links confirmed or contradicted here are reflected in Graphiti immediately
      and will be used by node_assemble_context on the next beat.
    - Manuscript ingestion (POST /alignment/ingest) starts ingestion/pipeline.py as a
      background asyncio task and streams progress via SSE.
"""

from quart import Blueprint, render_template, request

alignment_bp = Blueprint("alignment", __name__)


@alignment_bp.route("/alignment")
async def alignment_view():
    """
    Render the Alignment Dashboard Claim Card review view.

    Purpose:
        Serves templates/alignment.html with the rapid-throughput coreference review
        interface. Passes the count of pending provisional claims to the template.

    Inputs:
        None (GET request).

    Outputs:
        Rendered HTML response for the alignment template.
    """
    pass


@alignment_bp.route("/alignment/claims")
async def get_claims():
    """
    Return all pending provisional coreference claims as JSON.

    Purpose:
        Queries Graphiti for all edges tagged as provisional (mid-confidence) that
        have not yet been confirmed, contradicted, or resolved by the 200-token
        window heuristic. Returns them as Claim Card data for the frontend.

    Inputs:
        None (GET request).

    Outputs:
        JSON array of claim dicts:
        [{claim_id, pronoun_text, linked_entity_name, confidence, source_text_snippet}]
    """
    pass


@alignment_bp.route("/alignment/confirm", methods=["POST"])
async def confirm_claim():
    """
    Confirm a provisional coreference link, upgrading it to high-confidence.

    Purpose:
        Receives a claim_id from the frontend. Finds the corresponding provisional
        Graphiti edge and removes the provisional tag, making it a permanent
        high-confidence edge. The edge will be injected as absolute fact by
        node_assemble_context on subsequent beats.

    Inputs:
        POST body (JSON): {"claim_id": str}

    Outputs:
        JSON: {"status": "confirmed", "claim_id": str}
    """
    pass


@alignment_bp.route("/alignment/contradict", methods=["POST"])
async def contradict_claim():
    """
    Contradict a provisional coreference link, dropping the Graphiti edge.

    Purpose:
        Receives a claim_id from the frontend. Deletes the corresponding provisional
        Graphiti edge permanently. The dropped link will no longer be injected by
        node_assemble_context.

    Inputs:
        POST body (JSON): {"claim_id": str}

    Outputs:
        JSON: {"status": "contradicted", "claim_id": str}
    """
    pass


@alignment_bp.route("/alignment/ingest", methods=["POST"])
async def ingest():
    """
    Start manuscript ingestion as a background async task.

    Purpose:
        Accepts a manuscript file upload. Saves it to a temporary path and launches
        ingestion/pipeline.ingest_manuscript() as a background asyncio task.
        Returns immediately with 202 Accepted. Progress is streamed to the SSE endpoint.

    Inputs:
        POST body (multipart/form-data): manuscript file upload.

    Outputs:
        JSON: {"status": "ingestion_started"}
        HTTP 202 Accepted.
    """
    pass
