"""
routes/alignment.py

Alignment Dashboard Blueprint — Non-Blocking Coreference Claim Card Review.

Purpose:
    Provides the optional, non-blocking UI for reviewing provisional coreference
    assumptions generated by the ingestion pipeline. The FSM never waits for
    human review here — all coreference links are classified by confidence tier
    and the FSM proceeds with mid-confidence Epistemic Beliefs marked as unconfirmed.

    Claim Cards represent one provisional coreference link each. The author can:
    - Confirm a link (promotes it from provisional to confirmed in Graphiti).
    - Contradict a link (drops the edge from Graphiti).
    - Skip a link (leaves it as provisional for the 200-token window heuristic
      in node_commit_transaction to resolve automatically at chapter boundaries).

    Key routes:
    GET  /alignment          — Renders the Claim Card review view (templates/alignment.html).
    GET  /alignment/claims   — Returns JSON array of pending provisional coreference claims.
    POST /alignment/confirm  — Confirms a provisional link (upgrades to high-confidence).
    POST /alignment/contradict — Contradicts a provisional link (drops Graphiti edge).
    POST /alignment/ingest   — Initiates manuscript ingestion as a background async task.

Architecture role:
    - All human review actions are non-blocking — the FSM does not pause awaiting them.
    - Provisional links confirmed or contradicted here are reflected in Graphiti immediately
      and will be used by node_assemble_context on the next beat.
    - Manuscript ingestion (POST /alignment/ingest) starts ingestion/pipeline.py as a
      background asyncio task and streams progress via SSE.
"""

from quart import Blueprint, render_template, request

alignment_bp = Blueprint("alignment", __name__)

# Strong references to in-flight ingestion tasks. The event loop holds tasks
# weakly — without this, a background ingestion can be garbage-collected
# mid-flight (the same failure mode core/generation_manager.py guards against).
_ingestion_tasks: set = set()


@alignment_bp.route("/alignment")
async def alignment_view():
    """Render the Alignment Dashboard with the pending-claim count."""
    from memory import provisional_store

    pending = provisional_store.list_pending()
    return await render_template("alignment.html", pending_count=len(pending))


@alignment_bp.route("/alignment/claims")
async def get_claims():
    """All pending provisional coreference claims as Claim Card data."""
    from memory import provisional_store

    return provisional_store.list_pending()


@alignment_bp.route("/alignment/confirm", methods=["POST"])
async def confirm_claim():
    """Confirm a provisional link → permanent high-confidence fact."""
    from memory import provisional_store

    payload = await request.get_json(force=True)
    if provisional_store.confirm(payload["claim_id"]):
        return {"status": "confirmed", "claim_id": payload["claim_id"]}
    return {"status": "error", "message": "unknown claim_id"}, 404


@alignment_bp.route("/alignment/contradict", methods=["POST"])
async def contradict_claim():
    """Contradict a provisional link → edge dropped permanently."""
    from memory import provisional_store

    payload = await request.get_json(force=True)
    if provisional_store.contradict(payload["claim_id"]):
        return {"status": "contradicted", "claim_id": payload["claim_id"]}
    return {"status": "error", "message": "unknown claim_id"}, 404


@alignment_bp.route("/alignment/ingest", methods=["POST"])
async def ingest():
    """Save an uploaded manuscript and launch background ingestion."""
    import asyncio
    import uuid

    from core import runtime
    from core.config_loader import load_config
    from ingestion.pipeline import ingest_manuscript

    files = await request.files
    if "manuscript" not in files:
        return {"status": "error", "message": "no 'manuscript' file in upload"}, 400
    upload = files["manuscript"]
    target = runtime.DATA_DIR / f"upload_{uuid.uuid4().hex[:8]}.txt"
    target.parent.mkdir(parents=True, exist_ok=True)
    await upload.save(target)

    from core.logger import get_app_logger
    log = get_app_logger()

    config = load_config()
    log.info("ingestion started: %s", target.name)
    task = asyncio.create_task(ingest_manuscript(target, config, "default"))
    _ingestion_tasks.add(task)

    def _on_done(t: asyncio.Task) -> None:
        _ingestion_tasks.discard(t)
        # A background task's exception is otherwise never observed — surface it.
        if not t.cancelled() and t.exception() is not None:
            log.error("ingestion failed for %s", target.name, exc_info=t.exception())
        else:
            log.info("ingestion complete: %s", target.name)

    task.add_done_callback(_on_done)
    return {"status": "ingestion_started", "file": target.name}, 202
